
import java.io.BufferedReader;
import java.io.Console;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iammt
 */
public class Start extends javax.swing.JFrame {
    private ObjectOutputStream oos;
    private ObjectInputStream ois;     
    private Socket client;

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThongTin = new javax.swing.JButton();
        btnTraCuu = new javax.swing.JButton();
        btnXepHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("TRA CỨU KẾT QUẢ HỌC TẬP SINH VIÊN");

        btnThongTin.setBackground(new java.awt.Color(204, 204, 255));
        btnThongTin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnThongTin.setText("Thông tin sinh viên ");
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });

        btnTraCuu.setBackground(new java.awt.Color(204, 204, 255));
        btnTraCuu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTraCuu.setText("Tra cứu điểm sinh viên");

        btnXepHang.setBackground(new java.awt.Color(204, 204, 255));
        btnXepHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXepHang.setText("Xếp hạng sinh viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnThongTin)
                .addGap(64, 64, 64)
                .addComponent(btnTraCuu)
                .addGap(69, 69, 69)
                .addComponent(btnXepHang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThongTin)
                    .addComponent(btnTraCuu)
                    .addComponent(btnXepHang))
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Start(Socket client) {
            this.client = client;
            try {
                // Tạo luồng ghi và đọc một lần và sử dụng chúng liên tục
                oos = new ObjectOutputStream(client.getOutputStream());
                ois = new ObjectInputStream(client.getInputStream());
            } catch (IOException e) {
                e.printStackTrace();
            }
            initComponents();
        }
    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        // TODO add your handling code here:
        // Gửi yêu cầu đến máy chủ
        System.out.println("vo ne m ");
    
    String response = sendRequestToServer("ThongTinRequest");
    

    // Kiểm tra phản hồi từ máy chủ
        System.out.println("response"+response);
    if (response!=null&&response.equals("ChuyenHuong")) {
        // Nếu máy chủ trả về "ChuyenHuong", chuyển hướng đến form NhapThongTin
        NhapThongTin nhapThongTinForm = new NhapThongTin();
        nhapThongTinForm.setVisible(true);
        this.dispose(); // Đóng form hiện tại sau khi chuyển hướng
    } else {
        // Xử lý trường hợp khác (nếu cần)
    }
    }//GEN-LAST:event_btnThongTinActionPerformed

    private String sendRequestToServer(String request) {
        RequestSendToServer requestSendToServer = new RequestSendToServer("navigate", request);
        try {
            // Gửi yêu cầu đến máy chủ và nhận phản hồi
            oos.writeObject(requestSendToServer);
            oos.flush();
             Object response = ois.readObject();
             

            if (response instanceof String) {
                return  (String) response;
            }
            return "";
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);
            e.printStackTrace();
            return "LoiKetNoi";
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         Socket client = new Socket("localhost", 9999);
        
        java.awt.EventQueue.invokeLater(() -> {
            new Start(client).setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnTraCuu;
    private javax.swing.JButton btnXepHang;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
